[package]
name = "frametime-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
qualified-shader-cache-delete = ["frametime-windows/qualified-shader-cache-delete"]

[[bin]]
name = "frametime"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
frametime-core = { path = "../frametime-core" }
frametime-driver = { path = "../frametime-driver" }
frametime-hardware = { path = "../frametime-hardware" }
frametime-hardware-windows = { path = "../frametime-hardware-windows" }
frametime-windows = { path = "../frametime-windows" }
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
