version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      frametime-rust:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/rust/northclock"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      northclock-rust:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/rust/northclock/driver"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      northclock-driver-rust:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/rust/driver-foundry"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      driver-foundry-rust:
        patterns:
          - "*"
