//! Catalog signing probe and explicit Not-WHQL reporting.

use std::fs;
use std::path::Path;

use crate::pipeline::note;
use crate::tweaks::collect_display_driver_infs;

#[derive(Debug, Clone)]
pub(crate) struct SignAttempt {
    pub(crate) tools_present: bool,
    /// True only when a real successful catalog/driver sign was proven (not mere verify probe).
    pub(crate) proven_signed: bool,
}

/// Write a non-executing sign plan. PATH and mutable embedded signtool binaries are not trusted.
pub(crate) fn try_sign_catalog(prepared: &Path, log: &mut Vec<String>) -> SignAttempt {
    note(
        log,
        "S4-RebuildCatalog",
        &format!(
            "sign plan only; helper execution disabled for {}",
            prepared.display()
        ),
    );

    // Catalog rebuild plan: list INF files that would be signed.
    let infs = collect_display_driver_infs(prepared);
    let mut plan = String::from(
        "# Driver Foundry sign / catalog rebuild plan\n\
         # Generated by Driver Foundry try-sign path\n\
         # Signing without a trusted cert will fail; Not WHQL until proven success.\n\n",
    );
    if infs.is_empty() {
        plan.push_str("# (no INF files found under Display.Driver*)\n");
    } else {
        plan.push_str(&format!("# {} INF file(s) would be signed:\n", infs.len()));
        for p in &infs {
            plan.push_str(&format!("{}\n", p.display()));
        }
    }
    plan.push_str("\n# execution\n# disabled: no authenticated signtool release manifest\n");
    let plan_path = prepared.join("driver-foundry-sign-plan.txt");
    if let Err(e) = fs::write(&plan_path, &plan) {
        note(
            log,
            "S4-RebuildCatalog",
            &format!("failed to write sign plan: {e}"),
        );
    } else {
        note(
            log,
            "S4-RebuildCatalog",
            &format!(
                "sign plan written: {} ({} INF target(s))",
                plan_path.display(),
                infs.len()
            ),
        );
    }

    SignAttempt {
        tools_present: false,
        proven_signed: false,
    }
}
