use crate::*;

/// Read-only recovery inventory for presentation adapters.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BackupSummary {
    pub entries: Vec<BackupSummaryEntry>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BackupSummaryEntry {
    pub kind: String,
    pub count: usize,
}

/// Returns human-readable guidance generated by completed read-only catalog
/// steps. The application includes these in its typed run summary; adapters
/// decide whether and how to present them.
pub fn read_presentable_step_messages(
    steps: &[Step],
    state: &State,
) -> Result<Vec<String>, String> {
    let mut messages = Vec::new();
    for step in steps {
        let action = descriptor_for(step)?.action;
        if let Some(message) = guidance_message(&action) {
            messages.push(message.into());
        }
        if matches!(action, Action::FpsCapInfo) {
            messages.extend(fps_cap_info_messages(state));
        }
    }
    Ok(messages)
}

/// Returns persisted recovery-record counts without running an external tool.
pub fn read_backup_summary() -> Result<BackupSummary, String> {
    let trusted = TrustedWorkDir::acquire_fixed()?;
    let backup: BackupFile = read_json_trusted(&trusted, BACKUP_FILE)
        .map_err(|error| format!("read backup: {error}"))?;
    let mut counts = BTreeMap::<&str, usize>::new();
    for entry in &backup.entries {
        *counts.entry(backup_entry_kind(entry)).or_default() += 1;
    }
    Ok(BackupSummary {
        entries: counts
            .into_iter()
            .map(|(kind, count)| BackupSummaryEntry {
                kind: kind.into(),
                count,
            })
            .collect(),
    })
}

/// Reads the current file-backed log without executing a command.
pub fn read_log() -> Result<String, String> {
    let trusted = TrustedWorkDir::acquire_fixed()?;
    #[cfg(windows)]
    {
        crate::trust::io_windows::read_current_log(&trusted)
    }
    #[cfg(not(windows))]
    {
        let _ = trusted;
        Err("log display requires supported Windows x64".into())
    }
}

/// Run only the catalogued P1:16 NIC latency transaction through the normal
/// engine. The caller keeps consent in the application layer and supplies the
/// non-cloneable package capability that authorizes the mutation.
pub fn run_network_stack_transaction(
    package: &AuthenticatedPackage,
) -> Result<frametime_domain::RunReport, String> {
    let step = network_stack_step()?;
    let state = load_state()?;
    let progress = load_progress()?;
    let backend = LiveBackend::from_package(package)?;
    let mut engine = frametime_domain::Engine::new(backend, progress);
    engine
        .run_with_consent(&[step], state.profile, |_| true)
        .map_err(|error| error.to_string())
}

/// Deploy an explicitly selected closed set of embedded CS2 CFGs without
/// changing P1:34 progress, optimization.cfg, or autoexec.cfg. Exact original
/// bytes are persisted before mutation and remain available to recovery.
pub fn deploy_optional_cs2_cfgs(
    _package: &AuthenticatedPackage,
    assets: &[OptionalCfgAsset],
) -> Result<Vec<PathBuf>, String> {
    let selected = assets.iter().copied().collect::<BTreeSet<_>>();
    if selected.is_empty() {
        return Err("select at least one optional CS2 CFG".into());
    }
    let trusted = TrustedWorkDir::acquire_fixed()?;
    require_elevation()?;
    let _lock = WorkLock::acquire(trusted.path())?;
    let install = discover_trusted_cs2_config_install()?
        .ok_or("no trusted CS2 install exists under HKCU SteamPath")?;
    let mut files = NativeCs2ConfigFs::new(&install)
        .map_err(|error| format!("bind trusted optional CS2 CFG filesystem: {error}"))?;
    let entry = BackupEntry::capture_optional_cs2_config_transaction(
        &install,
        &selected,
        &timestamp(),
        &mut files,
    )
    .map_err(|error| format!("capture optional CS2 CFG transaction: {error}"))?;
    let backup_path = trusted.path().join(BACKUP_FILE);
    let mut backup = if backup_path.exists() {
        read_json_trusted(&trusted, BACKUP_FILE).map_err(|error| format!("read backup: {error}"))?
    } else {
        BackupFile {
            entries: Vec::new(),
            created: timestamp(),
            unknown: BTreeMap::new(),
        }
    };
    backup.push_first_value(entry.clone());
    write_json_atomic_trusted(&trusted, BACKUP_FILE, &backup)
        .map_err(|error| format!("persist optional CS2 CFG backup: {error}"))?;

    reobserve_trusted_cs2_config_install(&install, "optional CFG mutation")?;

    let written = entry
        .apply_optional_cs2_config_transaction(&install, &mut files)
        .map_err(|error| format!("deploy optional CS2 CFGs: {error}"))?;
    let controller = Cs2ConfigController::new(install)
        .map_err(|error| format!("validate optional CS2 CFG controller: {error}"))?;
    controller
        .verify_optional_assets(&selected, &mut files)
        .map_err(|error| format!("verify optional CS2 CFGs: {error}"))?;
    Ok(written)
}

pub(crate) fn network_stack_step() -> Result<frametime_domain::Step, String> {
    let mut matches = frametime_domain::step_catalog()
        .iter()
        .filter(|step| step.id.phase == frametime_domain::Phase::One && step.id.number == 16)
        .copied();
    let step = matches
        .next()
        .ok_or("compiled catalog is missing P1:16 NIC Latency Stack")?;
    if matches.next().is_some() {
        return Err("compiled catalog contains duplicate P1:16 steps".into());
    }
    Ok(step)
}

/// Replace progress atomically after the platform, path, and exclusive lock gates.
pub fn reset_progress(_package: &AuthenticatedPackage) -> Result<(), String> {
    let trusted = TrustedWorkDir::acquire_fixed()?;
    let work_dir = trusted.path();
    let _lock = WorkLock::acquire(work_dir)?;
    write_json_atomic_trusted(&trusted, PROGRESS_FILE, &Progress::default())
        .map_err(|error| format!("reset progress: {error}"))
}

/// Restore all recognised recovery records in reverse capture order.
///
/// Invalid, unknown, and failed entries remain in `backup.json`; successful
/// entries are removed atomically, so a subsequent run is a bounded retry.
pub fn restore_all_from_package(package: &AuthenticatedPackage) -> Result<(), String> {
    restore_matching(package.config(), |_| true)
}

/// Restore all records through the retained runtime selected for a resumed
/// transaction. This is intentionally separate from package recovery.
pub fn restore_all_from_runtime(runtime: &VerifiedSelectedRuntime) -> Result<(), String> {
    restore_matching(runtime.config(), |_| true)
}

/// Restore only records captured for an exact catalog step title. Records for
/// other steps, unknown records, and failed restores remain byte-compatible in
/// the active backup file for later retry.
pub fn restore_selected_from_package(
    package: &AuthenticatedPackage,
    step_title: &str,
) -> Result<(), String> {
    if step_title.is_empty() || step_title.len() > 128 {
        return Err("restore step title is invalid".into());
    }
    restore_matching(package.config(), |entry| entry.step() == Some(step_title))
}

pub(crate) fn restore_matching(
    config: &VerifiedConfig,
    selected: impl Fn(&BackupEntry) -> bool,
) -> Result<(), String> {
    let trusted = TrustedWorkDir::acquire_fixed()?;
    let work_dir = trusted.path();
    require_elevation()?;
    let _lock = WorkLock::acquire(work_dir)?;
    let mut backup: BackupFile = read_json_trusted(&trusted, BACKUP_FILE)
        .map_err(|error| format!("read backup: {error}"))?;
    let mut retained = Vec::new();
    let mut failures = Vec::new();
    for entry in backup.restore_order() {
        if !selected(entry) {
            retained.push(entry.clone());
            continue;
        }
        match restore_entry(entry, config.value()) {
            Ok(()) => {}
            Err(error) => {
                retained.push(entry.clone());
                failures.push(error);
            }
        }
    }
    retained.reverse();
    backup.entries = retained;
    write_json_atomic_trusted(&trusted, BACKUP_FILE, &backup)
        .map_err(|error| format!("persist restored backup: {error}"))?;
    if failures.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "{} recovery entries retained: {}",
            failures.len(),
            failures.join("; ")
        ))
    }
}

/// Clear recovery records only after the caller's explicit confirmation. The
/// operation is lock-protected and atomically replaces the active JSON file.
pub fn clear_backup(_package: &AuthenticatedPackage) -> Result<(), String> {
    let trusted = TrustedWorkDir::acquire_fixed()?;
    let work_dir = trusted.path();
    require_elevation()?;
    let _lock = WorkLock::acquire(work_dir)?;
    let backup: BackupFile = read_json_trusted(&trusted, BACKUP_FILE)
        .map_err(|error| format!("read backup before clear: {error}"))?;
    let cleared = BackupFile {
        entries: Vec::new(),
        created: backup.created,
        unknown: backup.unknown,
    };
    write_json_atomic_trusted(&trusted, BACKUP_FILE, &cleared)
        .map_err(|error| format!("clear backup: {error}"))
}

/// Export the exact active backup bytes after a constrained fixed-root read
/// and byte-for-byte destination verification.
pub fn export_backup(destination: &Path) -> Result<(), String> {
    let trusted = TrustedWorkDir::acquire_fixed()?;
    #[cfg(windows)]
    {
        // An existing destination is accepted only after it is opened as the
        // exact regular file with no sharing. It is then truncated and
        // replaced through that retained handle, never through a later path.
        crate::trust::io_windows::export_backup(&trusted, destination)
    }
    #[cfg(not(windows))]
    {
        let _ = (trusted, destination);
        Err("backup export requires supported Windows x64".into())
    }
}

#[cfg(test)]
mod backend_public_tests {
    use super::network_stack_step;

    #[test]
    pub(crate) fn network_facade_selects_only_p1_16() {
        let step = network_stack_step().expect("compiled network step");
        assert_eq!(step.id.phase as u8, 1);
        assert_eq!(step.id.number, 16);
        assert_eq!(step.title, "RSS Baseline");
    }

    #[test]
    pub(crate) fn public_mutation_facades_require_retained_authority() {
        let facade = include_str!("public.rs");
        let construction = include_str!("construction.rs");
        let persistence = include_str!("../storage/persistence.rs");
        let driver = include_str!("../driver/transaction_backend.rs");
        let reboot = include_str!("../reboot/handoff.rs");
        let trusted_root = include_str!("../trust/public.rs");
        assert!(facade.contains("package: &AuthenticatedPackage"));
        assert!(facade.contains("runtime: &VerifiedSelectedRuntime"));
        let legacy_restore = ["pub fn restore_all(", "work_dir"].concat();
        let legacy_network = ["pub fn run_network_stack_transaction(\n    ", "work_dir"].concat();
        assert!(!facade.contains(&legacy_restore));
        assert!(!facade.contains(&legacy_network));
        assert!(!construction.contains("pub fn new(work_dir: PathBuf, config: VerifiedConfig)"));
        assert!(construction.contains("pub fn from_package"));
        assert!(construction.contains("pub fn from_runtime"));
        for (source, function, authority) in [
            (persistence, "configure_profile", "&AuthenticatedPackage"),
            (persistence, "persist_fps_capture", "&AuthenticatedPackage"),
            (
                persistence,
                "persist_baseline_benchmark",
                "&AuthenticatedPackage",
            ),
            (
                persistence,
                "persist_final_benchmark",
                "&VerifiedSelectedRuntime",
            ),
            (persistence, "cleanup_quick", "&AuthenticatedPackage"),
            (persistence, "cleanup_full", "&AuthenticatedPackage"),
            (driver, "prepare_nvidia_driver", "&AuthenticatedPackage"),
            (
                driver,
                "remove_prepared_nvidia_driver",
                "&VerifiedSelectedRuntime",
            ),
            (
                driver,
                "install_prepared_nvidia_driver",
                "&VerifiedSelectedRuntime",
            ),
            (reboot, "arm_safe_mode_handoff", "&VerifiedSelectedRuntime"),
            (
                reboot,
                "clear_phase_three_handoff",
                "&VerifiedSelectedRuntime",
            ),
        ] {
            let signature = source
                .split_once(&format!("pub fn {function}"))
                .expect("public mutation facade exists")
                .1
                .split_once(") ->")
                .expect("public mutation signature ends")
                .0;
            assert!(
                signature.contains(authority),
                "{function} must require {authority}, never VerifiedConfig alone"
            );
            assert!(
                !signature.contains("work_dir"),
                "{function} must not accept a caller-selected work directory"
            );
        }
        assert!(trusted_root.contains("pub(crate) fn acquire(work_dir: &Path)"));
    }
}
