use frametime_app::{Branch, DryRunSummary};
use frametime_domain::catalog::{Step, step_catalog};
use serde_json::{Map, Value, json};

const ASSIGNMENT: &str = "window.FRAMETIME_REGISTER = ";
const BRANCHES: [(&str, &str, Branch); 4] = [
    ("1", "NVIDIA RTX 5000", Branch::NvidiaRtx5000),
    ("2", "Other NVIDIA", Branch::Nvidia),
    ("3", "AMD Radeon", Branch::Amd),
    ("4", "Intel Arc", Branch::IntelArc),
];

pub(crate) fn print() -> Result<(), String> {
    let register = build()?;
    println!("// Generated by `frametime site-register`; do not edit by hand.");
    println!("{ASSIGNMENT}{register};");
    Ok(())
}

fn build() -> Result<Value, String> {
    let branches = BRANCHES
        .into_iter()
        .map(|(key, label, branch)| build_branch(key, label, branch))
        .collect::<Result<Vec<_>, _>>()?;
    let steps = step_catalog().iter().map(step_value).collect::<Vec<_>>();

    Ok(json!({
        "command": "frametime dry-run all",
        "branches": branches,
        "steps": steps,
    }))
}

fn build_branch(key: &str, label: &str, branch: Branch) -> Result<Value, String> {
    let preview = frametime_app::run_dry(branch).map_err(|error| error.to_string())?;
    let lines = preview_lines(preview)?;
    let results = step_catalog()
        .iter()
        .zip(lines)
        .map(|(step, line)| {
            (
                step.id.progress_key(),
                json!({ "v": verdict(step, &line), "line": line }),
            )
        })
        .collect::<Map<_, _>>();

    Ok(json!({ "key": key, "label": label, "results": results }))
}

fn preview_lines(preview: DryRunSummary) -> Result<Vec<String>, String> {
    let lines = preview
        .lines
        .into_iter()
        .filter_map(|line| line.strip_prefix("[DRY-RUN] ").map(str::to_owned))
        .collect::<Vec<_>>();
    if lines.len() != step_catalog().len() {
        return Err(format!(
            "dry-run emitted {} register lines for {} catalog steps",
            lines.len(),
            step_catalog().len()
        ));
    }
    Ok(lines)
}

fn step_value(step: &Step) -> Value {
    json!({
        "id": step.id.progress_key(),
        "category": step.category,
        "title": step.title,
        "tier": step.tier,
        "risk": format!("{:?}", step.risk),
        "check": step.check_only,
        "reboot": step.reboot,
    })
}

fn verdict(step: &Step, line: &str) -> &'static str {
    if line.starts_with("Would skip inapplicable") {
        "skip"
    } else if line.contains(" is advisory and unverified: ") {
        "keep"
    } else if line.starts_with("Would require a complete VProf capture") {
        "evidence"
    } else if step.check_only {
        "inspect"
    } else {
        "change"
    }
}
