[package]
name = "northclock-fuzz"
version = "0.0.0"
edition = "2021"
license = "MIT"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]
resolver = "2"

[dependencies]
libfuzzer-sys = "0.4"
northclock-core = { path = "../crates/northclock-core", version = "=0.1.0-alpha.1" }
northclock-driver-protocol = { path = "../driver/crates/northclock-driver-protocol", version = "=0.1.0-alpha.1" }
northclock-platform-windows = { path = "../crates/northclock-platform-windows", version = "=0.1.0-alpha.1", features = ["fuzzing"] }

[[bin]]
name = "rom"
path = "fuzz_targets/rom.rs"
test = false
doc = false
bench = false

[[bin]]
name = "driver_protocol"
path = "fuzz_targets/driver_protocol.rs"
test = false
doc = false
bench = false

[[bin]]
name = "etw_abi"
path = "fuzz_targets/etw_abi.rs"
test = false
doc = false
bench = false

[[bin]]
name = "vendor_abi"
path = "fuzz_targets/vendor_abi.rs"
test = false
doc = false
bench = false
