use super::*;

#[rustfmt::skip]
pub static STEPS: [Step; 54] = [
    s!( One, 1, "System", "Configuration", 1, Safe, Setup, Configuration, false, false),
    s!( One, 2, "Hardware", "XMP/EXPO Check", 1, Safe, Check, XmpExpoCheck, true, false),
    s!( One, 3, "GPU", "Shader Cache Health", 1, Safe, Check, ShaderCacheHealth, true, false),
    s!( One, 4, "Display", "Fullscreen Optimizations Check", 1, Safe, Check, FullscreenOptimizationsCheck, true, false),
    s!( One, 5, "GPU", "NVIDIA Driver Version Inventory", 1, Safe, Check, NvidiaDriverInventory, true, false),
    s!( One, 6, "System", "Power Policy Guidance", 1, Safe, Check, PowerPolicyGuidance, true, false),
    s!( One, 7, "GPU", "HAGS Check", 2, Safe, Check, HagsCheck, true, false),
    s!( One, 8, "System", "Pagefile", 2, Moderate, Registry, Pagefile, false, true),
    s!( One, 9, "GPU", "Resizable BAR", 2, Safe, Check, ResizableBarCheck, true, true),
    s!( One, 10, "System", "Windows Timer Defaults", 3, Safe, Check, WindowsTimerDefaults, true, false),
    s!( One, 11, "Display", "MPO Health Check", 3, Safe, Check, MpoHealthCheck, true, false),
    s!( One, 12, "System", "Game Mode", 1, Safe, Registry, GameMode, false, false),
    s!( One, 13, "System", "Background App Guidance", 2, Safe, Check, BackgroundAppGuidance, true, false),
    s!( One, 14, "System", "Autostart Inventory", 2, Safe, Check, AutostartInventory, true, false),
    s!( One, 15, "System", "Windows Update Status", 3, Safe, Check, WindowsUpdateStatus, true, false),
    s!( One, 16, "Network", "RSS Baseline", 1, Safe, Network, RssBaseline, false, true),
    s!( One, 17, "Benchmark", "Baseline Benchmark", 1, Safe, Check, BaselineBenchmark, true, false),
    s!( One, 18, "GPU", "GPU Driver Clean (prep)", 1, Safe, Check, GpuDriverCleanPreparation, true, false),
    s!( One, 19, "GPU", "NVIDIA Driver Download", 1, Safe, Check, NvidiaDriverDownloadPreparation, true, false),
    s!( One, 20, "GPU", "NVIDIA Profile (prep)", 3, Safe, Check, NvidiaProfilePreparation, true, false),
    s!( One, 21, "Hardware", "MSI Interrupts (prep)", 2, Safe, Check, MsiPreparation, true, false),
    s!( One, 22, "Network", "NIC Interrupt Affinity (prep)", 3, Safe, Check, NicAffinityPreparation, true, false),
    s!( One, 23, "System", "Fast Startup Check", 2, Safe, Check, FastStartupGuidance, true, false),
    s!( One, 24, "Hardware", "Dual-Channel RAM", 1, Safe, Check, MemoryTopology, true, false),
    s!( One, 25, "Network", "TCP Defaults Check", 2, Safe, Check, TcpDefaultsGuidance, true, false),
    s!( One, 26, "Display", "Fullscreen Presentation Defaults", 2, Safe, Check, FullscreenPresentationGuidance, true, false),
    s!( One, 27, "System", "Scheduler Defaults", 2, Safe, Check, MultimediaDefaultsGuidance, true, false),
    s!( One, 28, "System", "Timer Defaults", 2, Safe, Check, TimerRequestGuidance, true, false),
    s!( One, 29, "Input", "Pointer Preference Check", 2, Safe, Check, PointerPreferenceGuidance, true, false),
    s!( One, 30, "GPU", "CS2 GPU Preference", 2, Moderate, Registry, Cs2HighPerformanceGpu, false, false),
    s!( One, 31, "System", "Capture Feature Check", 2, Safe, Check, GameDvrGuidance, true, false),
    s!( One, 32, "System", "Overlay Conflict Check", 2, Safe, Check, OverlayGuidance, true, false),
    s!( One, 33, "Audio", "Audio Path Check", 2, Safe, Check, AudioStackGuidance, true, false),
    s!( One, 34, "CS2", "optimization.cfg (fps_max only)", 2, Moderate, App, Cs2Configuration, false, false),
    s!( One, 35, "System", "Chipset Driver Check", 2, Safe, Check, ChipsetDriverInventory, true, false),
    s!( One, 36, "Display", "Visual Effects + Auto HDR Check", 3, Safe, Check, VisualEffectsGuidance, true, false),
    s!( One, 37, "System", "Service Status Check", 3, Safe, Check, WindowsServicesGuidance, true, false),
    s!( One, 38, "System", "Driver Repair: Activate Safe Mode", 3, Critical, Boot, SafeModeHandoff, false, true),
    s!( Two, 1, "Boot", "Disable Safe Mode", 1, Moderate, Boot, ClearSafeBoot, false, true),
    s!( Two, 2, "GPU", "GPU Driver Clean Removal", 1, Critical, Driver, NvidiaDriverRemoval, false, true),
    s!( Two, 3, "System", "Register Phase 3 for next boot", 1, Moderate, Registry, PhaseThreeHandoff, false, true),
    s!( Three, 1, "GPU", "Install NVIDIA Driver", 1, Moderate, Driver, NvidiaDriverInstall, false, true),
    s!( Three, 2, "GPU", "MSI Interrupt Guidance", 2, Safe, Check, MsiInterrupts, true, false),
    s!( Three, 3, "Network", "NIC Interrupt-Affinity Guidance", 3, Safe, Check, NicInterruptAffinity, true, false),
    s!( Three, 4, "GPU", "NVIDIA DRS Profile", 3, Safe, Driver, NvidiaProfileApply, false, false),
    s!( Three, 5, "CS2", "FPS Cap Info", 1, Safe, Check, FpsCapInfo, true, false),
    s!( Three, 6, "CS2", "Launch Options + Video Guidance", 2, Safe, App, Cs2LaunchVideoGuidance, true, false),
    s!( Three, 7, "Security", "VBS / Core Isolation Check", 2, Safe, Check, VbsHvciGuidance, true, false),
    s!( Three, 8, "GPU", "AMD GPU Settings", 2, Safe, Check, AmdRadeonGuidance, true, false),
    s!( Three, 9, "Network", "DNS Resolver Check", 3, Safe, Check, DnsGuidance, true, false),
    s!( Three, 10, "CPU", "Process Priority Defaults", 3, Safe, Check, ProcessPriorityGuidance, true, false),
    s!( Three, 11, "System", "VRAM Usage Review", 2, Safe, Check, VramUsageGuidance, true, false),
    s!( Three, 12, "System", "Final Checklist", 1, Safe, Check, FinalChecklistGuidance, true, false),
    s!( Three, 13, "Benchmark", "Final Benchmark + FPS Strategy", 1, Safe, Check, FinalBenchmark, true, false),
];
